name: AdminMenu
main: Menu\Bastard
api: 3.0.0
version: 1.0
author: DragonBastard
description: Convenient menu for Admins
commands:
  admmenu:
    description: Open Admin Menu!
    usage: /admmenu